title: '1'
description: '2'
baseurl: ''
url: 'https://viajesacademicos.com.ve'
emails: []
address: []
phones: []
twitter: '7'
facebook: '6'
instagram: '8'
production: false
markdown: kramdown
encoding: UTF-8
collections:
  campamentos:
    output: true
  promociones:
    output: true
