title: q
description: w
baseurl: ''
url: 'https://viajesacademicos.com.ve'
emails:
  - e
address:
  - r
phones:
  - t
twitter: u
facebook: 'y'
instagram: i
production: false
markdown: kramdown
encoding: UTF-8
collections:
  campamentos:
    output: true
  promociones:
    output: true
