title: Asesoría en estudios internacionales
description: 'En Academic And Language tenemos más de 17 años de experiencia y contamos con personal especializado que le guiará en todo lo relacionado con alojamiento, visa, boleto aéreo y todos los detalles necesarios para hacer la elección del curso, destino e instituto que más le conviene.'
baseurl: ''
url: 'https://viajesacademicos.com.ve'
emails:
  - a@a.com
address:
  - Address
phones:
  - Phone
twitter: Twitter
facebook: Facebook
instagram: Insta
production: false
markdown: kramdown
encoding: UTF-8
collections:
  campamentos:
    output: true
  promociones:
    output: true
